package dev.dolu.userservice.models;

public enum OnboardingFeature {
    VERIFY_EMAIL,
    VERIFY_PHONE,
    COMPLETE_PROFILE,
    CREATE_FIRST_LISTING,
    SET_AVAILABLE_DATES,
    SET_PREFERRED_LANGUAGE,
    SET_PREFERRED_CURRENCY,
    SET_NOTIFICATION_PREFERENCES,
    SET_AVAILABLE_SLOTS,
    ADD_PAYMENT_METHOD,
    COMPLETE_PAYMENT_SETUP,
    CREATE_FIRST_LEASE,
    FEEDBACK_SURVEY
}

